export const FETCH_RENTAL = "FETCH_RENTAL";
export const FETCH_RENTAL_BY_ID_SCCESS = "FETCH_RENTAL_BY_ID_SCCESS";
export const FETCH_RENTAL_BY_ID_INIT = "FETCH_RENTAL_BY_ID_INIT";
export const FETCH_RENTAL_SCCESS = "FETCH_RENTAL_SCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
